#!/usr/bin/python

import os
#import matplotlib
from numpy import *
import sys
from pylab import *

params = {'legend.fontsize': 8}
rcParams.update(params)

#ax1 = subplot(5,1,1,title='1D 624 site Hubbard (APBC) DoS')
#data_DMFT=mlab.load('CDMFT/ldos_u0.00_ep0.05.dat',usecols=[0,1],unpack=True)
#data_NoReopt2=mlab.load('nImp2/NoReopt/EC-TDA_GFResponse_0.00',usecols=[0,2],unpack=True)
#data_Reopt2=mlab.load('nImp2/Reopt/EC-TDA_GFResponse_0.00',usecols=[0,2],unpack=True)
##data_NoReopt3=mlab.load('nImp3/NoReopt/Refresh/EC-TDA_GFResponse_0.00',usecols=[0,2],unpack=True)
##data_Reopt3=mlab.load('nImp3/Reopt/EC-TDA_GFResponse_0.00',usecols=[0,2],unpack=True)
#ax1.plot(data_DMFT[0],data_DMFT[1]/fac,linewidth=2,label='CDMFT (6,6)',color='b')
##ax1.plot(data_NoReopt2[0],data_NoReopt2[1],linewidth=1,label='2-site',linestyle='dashed',color='r')
#ax1.plot(data_Reopt2[0],data_Reopt2[1],linewidth=1,label='2-site',color='r')
##ax1.plot(data_NoReopt3[0],data_NoReopt3[1],linewidth=1,linestyle='dashed',label='3-site',color='g')
##ax1.plot(data_Reopt3[0],data_Reopt3[1],linewidth=1,label='3-site ReoptGS',color='g')
#ax1.annotate('U = 0',xy=(-5,26),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
#ax1.legend(loc=2)
#setp(ax1.get_xticklabels(),visible=False)
#setp(ax1.get_yticklabels(),visible=False)
#xlim(-7,7)

ax2 = subplot(3,2,1)
data=mlab.load('U1/EC-TDA_GFResponse_1.00_All',usecols=[0,2],unpack=True)
ax2.plot(data[0],data[1]*2.0,linewidth=2,color='b')
ax2.annotate('U = 1t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
xlim(-3.5,3.5)
ylabel(r'$A(\omega)$')
#setp(ax2.get_xticklabels(),visible=False)
setp(ax2.get_yticklabels(),visible=False)
#xlim(-7,7)
ax3 = subplot(3,2,2)
data=mlab.load('U2/EC-TDA_GFResponse_2.00_All',usecols=[0,2],unpack=True)
ax3.plot(data[0],data[1]*2.0,linewidth=2,color='b')
ax3.annotate('U = 2t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
xlim(-3.5,3.5)
#setp(ax2.get_xticklabels(),visible=False)
setp(ax3.get_yticklabels(),visible=False)
#xlim(-7,7)
ax4 = subplot(3,2,3)
data=mlab.load('U3/EC-TDA_GFResponse_3.00_All',usecols=[0,2],unpack=True)
ax4.plot(data[0],data[1],linewidth=2,color='b')
ax4.annotate('U = 3t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
ylabel(r'$A(\omega)$')
xlim(-3.4,3.4)
#xlabel(r'$\omega$ / t')
#ylabel(r'$A(\omega)$')
#setp(ax2.get_xticklabels(),visible=False)
setp(ax4.get_yticklabels(),visible=False)
ax5 = subplot(3,2,4)
data=mlab.load('U4/EC-TDA_GFResponse_4.00_All',usecols=[0,2],unpack=True)
datab=mlab.load('U4/beta/EC-TDA_GFResponse_4.00_All',usecols=[0,2],unpack=True)
ax5.plot(data[0],data[1]+datab[1],linewidth=2,color='b')
ax5.annotate('U = 4t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
#setp(ax2.get_xticklabels(),visible=False)
setp(ax5.get_yticklabels(),visible=False)
xlim(-3.5,3.5)
#xlabel(r'$\omega$ / t')

ax6 = subplot(3,2,5)
data=mlab.load('U5/EC-TDA_GFResponse_5.00_All',usecols=[0,2],unpack=True)
datab=mlab.load('U5/beta/EC-TDA_GFResponse_5.00_All',usecols=[0,2],unpack=True)
ax6.plot(data[0],data[1]+datab[1],linewidth=2,color='b')
ax6.annotate('U = 5t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
#setp(ax2.get_xticklabels(),visible=False)
setp(ax6.get_yticklabels(),visible=False)
xlim(-3.5,3.5)
ylabel(r'$A(\omega)$')
xlabel(r'$\omega$ / t')
ax7 = subplot(3,2,6)
data=mlab.load('U6/EC-TDA_GFResponse_6.00_All',usecols=[0,2],unpack=True)
datab=mlab.load('U6/beta/EC-TDA_GFResponse_6.00_All',usecols=[0,2],unpack=True)
ax7.plot(data[0],data[1]+datab[1],linewidth=2,color='b')
ax7.annotate('U = 6t',xy=(-5,-10),xycoords='axes points',xytext=None, textcoords='offset points',horizontalalignment='right', verticalalignment='bottom',fontsize='16')
#setp(ax2.get_xticklabels(),visible=False)
setp(ax7.get_yticklabels(),visible=False)
xlim(-4,4)
xlabel(r'$\omega$ / t')

subplots_adjust(hspace=0.15,wspace=0.075)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(10,10)
plt.savefig('6Imp_Honeycomb.eps',dpi=100)

#show()
#avefig('2DHub_Spectra.eps')

#clf()
#
#for U in [1.0,2.0,4.0,6.0,8.0]:
#    data_DMFT=mlab.load('CDMFT/ldos_u%s0_ep0.05.dat' % str(U),usecols=[0,1],unpack=True)
#    data_NoReopt2=mlab.load('nImp2/NoReopt/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_Reopt2=mlab.load('nImp2/Reopt/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_NoReopt3_Ref=mlab.load('nImp3/NoReopt/Refresh/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_NoReopt3_Down=mlab.load('nImp3/NoReopt/RampDown/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_Reopt3_Ref=mlab.load('nImp3/Reopt/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_Reopt3_Down=mlab.load('nImp3/Reopt/RampDown/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#    data_NoReopt3_AntiTile=mlab.load('nImp3/NoReopt/Refresh/TileU/EC-TDA_GFResponse_%s0' % str(U),usecols=[0,2],unpack=True)
#
#    clf()
#    ax1 = subplot(111)
#    suptitle('Hubbard(APBC) 624 sites DoS: U = %s' % str(U))
#    ylabel(r'-$\Im [A_{1,1}]$')
#    xlabel(r'$\omega$ / t')
#    ax1.plot(data_DMFT[0],data_DMFT[1]/fac,linewidth=2,label='CDMFT(6,6)',color='b')
#    ax1.plot(data_NoReopt2[0],data_NoReopt2[1],linewidth=1,label='2-site',linestyle='dashed',color='g')
#    ax1.plot(data_Reopt2[0],data_Reopt2[1],linewidth=1,label='2-site (Reopt GS)',color='g')
#    ax1.plot(data_NoReopt3_Ref[0],data_NoReopt3_Ref[1],linewidth=1,label='3-site',linestyle='dashed',color='r')
#    ax1.plot(data_Reopt3_Ref[0],data_Reopt3_Ref[1],linewidth=1,label='3-site (Reopt GS)',color='r')
#    ax1.plot(data_NoReopt3_Down[0],data_NoReopt3_Down[1],linewidth=1,label='3-site (Ramp Down)',linestyle='dashed',color='c')
#    ax1.plot(data_Reopt3_Down[0],data_Reopt3_Down[1],linewidth=1,label='3-site (Ramp Down: Reopt GS)',color='c')
#    ax1.plot(data_NoReopt3_AntiTile[0],data_NoReopt3_AntiTile[1],linewidth=1,label='3-site, Anti-tile',color='r')
#    legend(loc=0)
##    ylim(-5,30)
##    savefig('Plot_%s.eps' % str(U))
#    show()
#    #savefig('GF_Hub_OBC_8Site_%s.png' % str(U))
#
##    dataDD_Exact=mlab.load('Exact/Exact_DDResponse_%s0' % str(U),usecols=[0,2],unpack=True)
##    dataDD_Reopt1=mlab.load('Reopt/nImp1/EC-TDA_DDResponse_%s0' % str(U),usecols=[0,2],unpack=True)
##    dataDD_Reopt2=mlab.load('Reopt/nImp2/EC-TDA_DDResponse_%s0' % str(U),usecols=[0,2],unpack=True)
##    dataDD_NoReopt1=mlab.load('NoReopt/nImp1/EC-TDA_DDResponse_%s0' % str(U),usecols=[0,2],unpack=True)
##    dataDD_NoReopt2=mlab.load('NoReopt/nImp2/EC-TDA_DDResponse_%s0' % str(U),usecols=[0,2],unpack=True)
##
##    clf()
##    ax1 = subplot(111)
##    suptitle('Hubbard(OBC) 8 sites DD response: U = %s' % str(U))
##    ylabel(r'-$\Im [A_{1,1}]$')
##    xlabel(r'$\omega$ / t')
##    ax1.plot(dataDD_Exact[0],dataDD_Exact[1],linewidth=2,label='Exact',color='b')
##    ax1.plot(dataDD_NoReopt1[0],dataDD_NoReopt1[1],linewidth=1,label='1-site',linestyle='dashed',color='g')
##    ax1.plot(dataDD_NoReopt2[0],dataDD_NoReopt2[1],linewidth=1,label='2-site',linestyle='dashed',color='r')
##    ax1.plot(dataDD_Reopt1[0],dataDD_Reopt1[1],linewidth=1,label='1-site ReoptGS',color='g')
##    ax1.plot(dataDD_Reopt2[0],dataDD_Reopt2[1],linewidth=1,label='2-site ReoptGS',color='r')
##    legend(loc=0)
##    ylim(-5,30)
##    savefig('Plot_%s.eps' % str(U))
#    #show()
#    #savefig('DD_Hub_OBC_8Site_%s.png' % str(U))
