#!/bin/bash
#
# PBS commands
#
#PBS -q l12
#PBS -l walltime=48:00:00
#PBS -m aeb


wd=$PBS_O_WORKDIR
scratch=/scratch/ghb24/job-$PBS_JOBID
nodescratch=ghb24/job-$PBS_JOBID

code=/home/ghb24/Code/LRDMET/bin/LRDMET.x

cd $PBS_O_WORKDIR


#
# Write out useful info to the nodefile
# 
echo "Listing files in scratch directory `pwd`:"
ls
echo
echo "Starting job $PBS_JOBID in $wd at `date`"
echo
echo "PBS assigned me node(s):"
cat $PBS_NODEFILE
echo ""
echo ""

$code input.model > OUT 

#mpiexec $neci $neci_in > $neci_out 2> $neci_err

echo "Finished job $PBS_JOBID in $wd at `date`"
echo ""
echo ""
qstat -f $PBS_JOBID
cd $wd
