#!/bin/bash
#PBS -l walltime=00:120:00:00
#PBS -l nodes=1:ppn=12
#PBS -m ae
#PBS -q chan 

SCRDIR="/scratch/georgehb/job-$PBS_JOBID"
TGRDIR="/tigress-hsm/georgehb/job-$PBS_JOBID"
CWDIR=$PBS_O_WORKDIR

#cd $CWDIR
#echo "prefix $SCRDIR " >> dmrg.inp
echo "Starting job $PBS_JOBID in $CWDIR at `date`"
echo
echo "PBS assigned me node(s):"
cat $PBS_NODEFILE
echo ""

block=/home/georgehb/Code/Block/Block.git/block.spin_adapted
neci=/home/georgehb/Code/NECI/RealCoeffs_new/bin/neci.x
lrdmet=/home/georgehb/Code/LRDMET/bin/LRDMET.x

echo "Creating scratch directory: ${SCRDIR}"

#mkdir -p /scratch/georgehb/
mkdir -p ${SCRDIR}
mkdir -p ${TGRDIR}
cd ${SCRDIR}

#rsync -avzr ${CWDIR}/ ${SCRDIR}
scp ${CWDIR}/* ${SCRDIR}
#mpirun -np 1 -bynode block.spin_adapted dmrg.inp > dmrg.out
$lrdmet input.model > output
#mpirun rsync -avzr ${SCRDIR}/ ${TGRDIR}

ls -1 | grep out* | xargs -i rsync -avzr {} $CWDIR
ls -1 | grep DMET* | xargs -i rsync -avzr {} $CWDIR
ls -1 | grep CORR* | xargs -i rsync -avzr {} $CWDIR
ls -1 | grep EC-TDA* | xargs -i rsync -avzr {} $CWDIR

cd $CWDIR

#
#
#
#rsync -avzr --include-from=/home/ro3/scripts/rsync_include.dmrg ${SCRDIR}/ ${CWDIR}
#
##rsync.include 
#+ */
#+ FCIDUMP
#+ *inp
#+ reorder.dat
#+ *out
#+ *.o[0-9][0-9][0-9][0-9][0-9][0-9]
#+ *.e[0-9][0-9][0-9][0-9][0-9][0-9]
#- *
